export const DATA_SOURCE = 'DATA_SOURCE';
export const SCHEDULER_REPOSITORY = 'SCHEDULER_REPOSITORY';
export const SCHEDULERS_HISTORY_REPOSITORY = 'SCHEDULERS_HISTORY_REPOSITORY';
export const SCRAPER_REPOSITORY = 'SCRAPER_REPOSITORY';
